---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
    - name: remove ec2
      ec2:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         region: 'us-east-1'
         state: 'absent'
         instance_ids: 'i-0775cc2e49dad5a5d'
 
