---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
    - name: security group creation
      ec2_group:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         region: "us-east-1"
         vpc_id: "vpc-477b1721"
         name: "full-traffic"
         description: "this SG related to full traffic"
         rules:
           - proto: all
